/**
 * `initGrok` — the Grok session-surface installer.
 *
 * One command wires a project into the session surface: prove `polydeukes` resolves, spawn
 * its agent-neutral scaffold (`pdks init`, which writes the config and the telemetry ignore
 * line), then add what this package owns — the delegator hook file and the Grok hook JSON
 * registration.
 *
 * Preflight comes first and nothing is written before it clears. A generated hook whose
 * import can never resolve blocks every call through its own fail-closed catch, and a tree
 * that also has no config and no valve to open cannot be edited back into shape from inside
 * the session.
 *
 * Nothing existing is overwritten. The installer does not read or write `.claude/` files.
 */

import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { findUmbrellaBin, UMBRELLA_PACKAGE } from './resolve-umbrella.ts';
import { MUTATING_TOOLS, SHELL_TOOLS } from './session-vocabulary.ts';

/** The package the generated delegator loads `runHook` from. */
const ADAPTER_SPECIFIER = '@polydeukes/adapter-grok';
/** The registration artifacts, as `projectRoot`-relative paths (the report vocabulary). */
const HOOK_RELATIVE = '.grok/hooks/covenant-pretooluse.mjs';
const JSON_RELATIVE = '.grok/hooks/covenant-pretooluse.json';
/**
 * The command the host spawns. `$GROK_WORKSPACE_ROOT` is this host's project-root
 * environment variable.
 */
const HOOK_COMMAND = `node "$GROK_WORKSPACE_ROOT"/${HOOK_RELATIVE}`;
/** Which calls reach the judge — this package's own vocabulary, never a copy of it. */
const HOOK_MATCHER = [...MUTATING_TOOLS, ...SHELL_TOOLS].join('|');

/**
 * The generated hook. It carries no assembly at all, so upgrading the package upgrades the
 * judge without regenerating this file.
 */
const GENERATED_HOOK = `#!/usr/bin/env node
/**
 * Polydeukes PreToolUse covenant hook — generated by \`pdks-grok init\`.
 *
 * A delegator and nothing more: \`runHook\` builds the covenant input from this payload and
 * spawns \`pdks covenant check\`, so the judgment lives in the installed packages and this
 * file never needs regenerating.
 *
 * \`repoRoot\` comes from this file's own location, never from the working directory. A hook
 * is spawned with whatever directory the agent happened to hold, and what config discovery
 * and the package lookup need is the project that CONTAINS this hook — always \`../..\`
 * from here.
 *
 * fail-closed: \`runHook\` translates every failure it can reach into exit 2, with the row
 * written by the judge it spawns. This catch answers only for what it cannot reach — the
 * package failing to resolve or load at all (never installed, or installed without a
 * build) — where no telemetry writer exists yet. Recovery is installing the package again.
 */

import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

try {
  const { runHook } = await import('${ADAPTER_SPECIFIER}');
  const { exitCode } = runHook({ repoRoot });
  // Assign and let the process end naturally instead of process.exit(): an explicit exit
  // can preempt a buffered stderr write on platforms with async pipes, dropping the break
  // reason the agent needs to read.
  process.exitCode = exitCode;
} catch (error) {
  console.error(\`covenant hook failed closed: \${error?.message ?? error}\`);
  process.exitCode = 2;
}
`;

const GENERATED_JSON = `${JSON.stringify(
  {
    hooks: {
      PreToolUse: [
        {
          matcher: HOOK_MATCHER,
          hooks: [{ type: 'command', command: HOOK_COMMAND, timeout: 60 }],
        },
      ],
    },
  },
  null,
  2,
)}\n`;

/** What one install left behind, per artifact. */
export type InitGrokReport = { created: string[]; skipped: string[] };

/** {@link initGrok} input — the target tree and its two seams. */
export type InitGrokSpec = {
  /** Project root to install into — every write below is relative to it. */
  projectRoot: string;
  /**
   * Preflight seam: the absolute path of the umbrella's `pdks` bin as reachable from the
   * given root, or a throw when the umbrella cannot be resolved there. ABSENT uses the real
   * resolution, anchored at that root and nowhere else — anchoring it at the installer's
   * own module would answer for the installer's install graph rather than the target
   * project's, which is precisely the case that must fail.
   */
  resolvePolydeukes?: (projectRoot: string) => string;
  /**
   * The `pdks init` spawn seam. ABSENT spawns node on the located bin with the child's
   * output inherited.
   */
  spawnScaffold?: (spec: { command: string; args: string[]; cwd: string }) => {
    status: number | null;
  };
};

/** The default preflight: where is `polydeukes` installed, as reachable from `projectRoot`? */
function resolveFromProjectRoot(projectRoot: string): string {
  const bin = findUmbrellaBin(projectRoot);
  if (bin === undefined) {
    throw new Error(`${UMBRELLA_PACKAGE} is not installed where this project can reach it`);
  }
  return bin;
}

/** Write one generated artifact unless it is already there, recording which happened. */
function writeIfAbsent(
  projectRoot: string,
  relative: string,
  contents: string,
  report: InitGrokReport,
): void {
  const path = join(projectRoot, relative);
  if (existsSync(path)) {
    report.skipped.push(relative);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
  report.created.push(relative);
}

/**
 * Install the Grok session surface into `spec.projectRoot`, skipping whatever is
 * already there and reporting both halves per artifact.
 *
 * Throws before any write when the umbrella cannot be resolved from that root or when
 * the scaffold refuses — both leave zero files. Translating a throw into exit 2 with the
 * install command is the bin's job.
 */
export function initGrok(spec: InitGrokSpec): InitGrokReport {
  const resolvePolydeukes = spec.resolvePolydeukes ?? resolveFromProjectRoot;
  let scaffoldBin: string;
  try {
    scaffoldBin = resolvePolydeukes(spec.projectRoot);
  } catch (error) {
    // The message names the package because the user's next action is installing it — the
    // seam's own message cannot be relied on to say so. The original is carried through
    // rather than discarded: an experimental resolver can fail for reasons that are
    // neither absence nor a stale version.
    throw new Error(
      `cannot use '${UMBRELLA_PACKAGE}' from ${spec.projectRoot} — install or update it there ` +
        `first (e.g. 'npm install --save-dev ${UMBRELLA_PACKAGE}'), then run this command ` +
        `again: ${error instanceof Error ? error.message : String(error)}`,
    );
  }

  const spawnScaffold =
    spec.spawnScaffold ??
    ((scaffold) =>
      spawnSync(scaffold.command, scaffold.args, { cwd: scaffold.cwd, stdio: 'inherit' }));
  const scaffold = spawnScaffold({
    command: process.execPath,
    args: [scaffoldBin, 'init'],
    cwd: spec.projectRoot,
  });
  if (scaffold.status !== 0) {
    // Any non-zero status is a scaffold that did not run: registering a delegator into a
    // tree with no config wires a judge whose every call fails closed.
    throw new Error(
      `'pdks init' failed in ${spec.projectRoot} (exit ${String(scaffold.status)}) — ` +
        'fix what it reported and re-run',
    );
  }

  const report: InitGrokReport = { created: [], skipped: [] };
  writeIfAbsent(spec.projectRoot, HOOK_RELATIVE, GENERATED_HOOK, report);
  writeIfAbsent(spec.projectRoot, JSON_RELATIVE, GENERATED_JSON, report);
  return report;
}
