/**
 * `initCodex` — the Codex session-surface installer.
 *
 * One command wires a project into the session surface: prove `polydeukes` resolves, spawn
 * its agent-neutral scaffold (`pdks init`, which writes the config and the telemetry ignore
 * line), then add what this package owns — the delegator hook file and the host's hook JSON
 * registration.
 *
 * Preflight comes first and nothing is written before it clears. A generated hook whose
 * import can never resolve blocks every call through its own fail-closed catch, and a tree
 * that also has no config and no valve to open cannot be edited back into shape from inside
 * the session.
 *
 * The host trusts a hook by the hash of its definition, so the registration is written from
 * a fixed template and merged into whatever the user already has: a re-run that changes one
 * character silences the judge until a human approves it again in `/hooks`.
 *
 * Nothing existing is overwritten. The installer does not read or write another host's files.
 */

import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { isPlainObject } from '@polydeukes/core';
import { findUmbrellaBin, UMBRELLA_PACKAGE } from './resolve-umbrella.ts';
import { MUTATING_TOOLS, SHELL_TOOLS } from './session-vocabulary.ts';

/** The package the generated delegator loads `runHook` from. */
const ADAPTER_SPECIFIER = '@polydeukes/adapter-codex';
/** The registration artifacts, as `projectRoot`-relative paths (the report vocabulary). */
const HOOK_RELATIVE = '.codex/hooks/covenant-pretooluse.mjs';
const JSON_RELATIVE = '.codex/hooks.json';
/**
 * The command the host spawns, project-relative. An absolute path would bake one checkout's
 * location into the string the trust hash covers, so the same package version would present
 * a different definition in every clone.
 */
const HOOK_COMMAND = `node ${HOOK_RELATIVE}`;
/** Which calls reach the judge — this package's own vocabulary, never a copy of it. */
const HOOK_MATCHER = [...SHELL_TOOLS, ...MUTATING_TOOLS].join('|');
/**
 * Seconds the host waits for the hook. A timed-out hook is treated as failed and the tool
 * call proceeds, and the default window is shorter than a cold judge process needs.
 */
const HOOK_TIMEOUT = 60;
/** The one event this adapter registers: the only one observed before the call runs. */
const HOOK_EVENT = 'PreToolUse';

/**
 * The generated hook. It carries no assembly at all, so upgrading the package upgrades the
 * judge without regenerating this file.
 */
const GENERATED_HOOK = `#!/usr/bin/env node
/**
 * Polydeukes PreToolUse covenant hook — generated by \`pdks-codex init\`.
 *
 * A delegator and nothing more: \`runHook\` builds the covenant input from this payload and
 * spawns \`pdks covenant check\`, so the judgment lives in the installed packages and this
 * file never needs regenerating.
 *
 * \`repoRoot\` comes from this file's own location, never from the working directory. A hook
 * is spawned with whatever directory the agent happened to hold, and what config discovery
 * and the package lookup need is the project that CONTAINS this hook — always \`../..\`
 * from here.
 *
 * fail-closed: \`runHook\` translates every failure it can reach into exit 2, with the row
 * written by the judge it spawns. This catch answers only for what it cannot reach — the
 * package failing to resolve or load at all (never installed, or installed without a
 * build) — where no telemetry writer exists yet. Recovery is installing the package again.
 *
 * Nothing is written to stdout here or by anything this file starts: the host parses a
 * hook's stdout as a decision document, and a field it does not accept marks the hook
 * failed and lets the tool call proceed.
 */

import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

try {
  const { runHook } = await import('${ADAPTER_SPECIFIER}');
  const { exitCode } = runHook({ repoRoot });
  // Assign and let the process end naturally instead of process.exit(): an explicit exit
  // can preempt a buffered stderr write on platforms with async pipes, dropping the break
  // reason the agent needs to read.
  process.exitCode = exitCode;
} catch (error) {
  console.error(\`covenant hook failed closed: \${error?.message ?? error}\`);
  process.exitCode = 2;
}
`;

/** This installer's registration entry — the exact object the trust hash is taken over. */
const OWN_ENTRY = {
  matcher: HOOK_MATCHER,
  hooks: [{ type: 'command', command: HOOK_COMMAND, timeout: HOOK_TIMEOUT }],
};

/** What one install left behind, per artifact. */
export type InitCodexReport = { created: string[]; skipped: string[] };

/** {@link initCodex} input — the target tree and its two seams. */
export type InitCodexSpec = {
  /** Project root to install into — every write below is relative to it. */
  projectRoot: string;
  /**
   * Preflight seam: the absolute path of the umbrella's `pdks` bin as reachable from the
   * given root, or a throw when the umbrella cannot be resolved there. ABSENT uses the real
   * resolution, anchored at that root and nowhere else — anchoring it at the installer's
   * own module would answer for the installer's install graph rather than the target
   * project's, which is precisely the case that must fail.
   */
  resolvePolydeukes?: (projectRoot: string) => string;
  /**
   * The `pdks init` spawn seam. ABSENT spawns node on the located bin with the child's
   * output inherited.
   */
  spawnScaffold?: (spec: { command: string; args: string[]; cwd: string }) => {
    status: number | null;
  };
};

/** The default preflight: where is `polydeukes` installed, as reachable from `projectRoot`? */
function resolveFromProjectRoot(projectRoot: string): string {
  const bin = findUmbrellaBin(projectRoot);
  if (bin === undefined) {
    throw new Error(`${UMBRELLA_PACKAGE} is not installed where this project can reach it`);
  }
  return bin;
}

/** Write one generated artifact unless it is already there, recording which happened. */
function writeIfAbsent(
  projectRoot: string,
  relative: string,
  contents: string,
  report: InitCodexReport,
): void {
  const path = join(projectRoot, relative);
  if (existsSync(path)) {
    report.skipped.push(relative);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
  report.created.push(relative);
}

/**
 * Add this installer's entry to the host's hook registration, keeping everything else.
 *
 * The file may already carry the user's own events, matchers, and keys, so it is merged
 * rather than written. Its own entry is found by matcher: found by identity, a re-run would
 * append a second one, and re-serialising a user's entry changes the hash of a definition
 * they already approved. An unreadable file throws — a file that cannot be merged into
 * cannot be overwritten either, and skipping it would leave the host unregistered with a
 * report saying otherwise.
 */
function mergeRegistration(projectRoot: string, report: InitCodexReport): void {
  const path = join(projectRoot, JSON_RELATIVE);
  if (!existsSync(path)) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, `${JSON.stringify({ hooks: { [HOOK_EVENT]: [OWN_ENTRY] } }, null, 2)}\n`);
    report.created.push(JSON_RELATIVE);
    return;
  }

  const existing: unknown = JSON.parse(readFileSync(path, 'utf-8'));
  if (!isPlainObject(existing)) {
    throw new Error(`${JSON_RELATIVE} is not a JSON object — repair it, then run this again`);
  }
  const hooks = isPlainObject(existing.hooks) ? existing.hooks : {};
  const event = Array.isArray(hooks[HOOK_EVENT]) ? (hooks[HOOK_EVENT] as unknown[]) : [];
  const isOwn = (entry: unknown) => isPlainObject(entry) && entry.matcher === HOOK_MATCHER;
  const others = event.filter((entry) => !isOwn(entry));

  const merged = {
    ...existing,
    hooks: { ...hooks, [HOOK_EVENT]: [...others, OWN_ENTRY] },
  };
  // Written or not written, reported as such: a merge that appends this entry to a file the
  // user already had changes its trust hash, so calling it skipped would tell them nothing
  // needs approving while the hook sits unapproved and unjudging.
  const text = `${JSON.stringify(merged, null, 2)}\n`;
  if (text === readFileSync(path, 'utf-8')) {
    report.skipped.push(JSON_RELATIVE);
    return;
  }
  writeFileSync(path, text);
  report.created.push(JSON_RELATIVE);
}

/**
 * Install the Codex session surface into `spec.projectRoot`, skipping whatever is already
 * there and reporting both halves per artifact.
 *
 * Throws before any write when the umbrella cannot be resolved from that root or when the
 * scaffold refuses — both leave zero files. Translating a throw into exit 2 with the install
 * command is the bin's job.
 */
export function initCodex(spec: InitCodexSpec): InitCodexReport {
  const resolvePolydeukes = spec.resolvePolydeukes ?? resolveFromProjectRoot;
  let scaffoldBin: string;
  try {
    scaffoldBin = resolvePolydeukes(spec.projectRoot);
  } catch (error) {
    // The message names the package because the user's next action is installing it — the
    // seam's own message cannot be relied on to say so. The original is carried through
    // rather than discarded: an experimental resolver can fail for reasons that are
    // neither absence nor a stale version.
    throw new Error(
      `cannot use '${UMBRELLA_PACKAGE}' from ${spec.projectRoot} — install or update it there ` +
        `first (e.g. 'npm install --save-dev ${UMBRELLA_PACKAGE}'), then run this command ` +
        `again: ${error instanceof Error ? error.message : String(error)}`,
    );
  }

  const spawnScaffold =
    spec.spawnScaffold ??
    ((scaffold) =>
      spawnSync(scaffold.command, scaffold.args, { cwd: scaffold.cwd, stdio: 'inherit' }));
  const scaffold = spawnScaffold({
    command: process.execPath,
    args: [scaffoldBin, 'init'],
    cwd: spec.projectRoot,
  });
  if (scaffold.status !== 0) {
    // Any non-zero status is a scaffold that did not run: registering a delegator into a
    // tree with no config wires a judge whose every call fails closed.
    throw new Error(
      `'pdks init' failed in ${spec.projectRoot} (exit ${String(scaffold.status)}) — ` +
        'fix what it reported and re-run',
    );
  }

  const report: InitCodexReport = { created: [], skipped: [] };
  writeIfAbsent(spec.projectRoot, HOOK_RELATIVE, GENERATED_HOOK, report);
  mergeRegistration(spec.projectRoot, report);
  return report;
}
