/**
 * `initCodex` — the Codex session-surface installer.
 *
 * One command wires a project into the session surface: prove `polydeukes` resolves, spawn
 * its agent-neutral scaffold (`pdks init`, which writes the config and the telemetry ignore
 * line), then add what this package owns — the delegator hook file and the host's hook JSON
 * registration.
 *
 * Preflight comes first and nothing is written before it clears. A generated hook whose
 * import can never resolve blocks every call through its own fail-closed catch, and a tree
 * that also has no config and no valve to open cannot be edited back into shape from inside
 * the session.
 *
 * The host trusts a hook by the hash of its definition, so the registration is written from
 * a fixed template and merged into whatever the user already has: a re-run that changes one
 * character silences the judge until a human approves it again in `/hooks`.
 *
 * Nothing existing is overwritten. The installer does not read or write another host's files.
 */

import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { isPlainObject } from '@polydeukes/core';
import { findUmbrellaBin, UMBRELLA_PACKAGE } from './resolve-umbrella.ts';
import { MUTATING_TOOLS, SHELL_TOOLS } from './session-vocabulary.ts';

/** The package the generated delegator loads `runHook` from. */
const ADAPTER_SPECIFIER = '@polydeukes/adapter-codex';
/** The registration artifacts, as `projectRoot`-relative paths (the report vocabulary). */
const HOOK_RELATIVE = '.codex/hooks/covenant-pretooluse.mjs';
const JSON_RELATIVE = '.codex/hooks.json';
/**
 * The command the host spawns, project-relative. An absolute path would bake one checkout's
 * location into the string the trust hash covers, so the same package version would present
 * a different definition in every clone.
 */
const HOOK_COMMAND = `node ${HOOK_RELATIVE}`;
/** Which calls reach the judge — this package's own vocabulary, never a copy of it. */
const HOOK_MATCHER = [...SHELL_TOOLS, ...MUTATING_TOOLS].join('|');
/**
 * Seconds the host waits for the hook. A timed-out hook is treated as failed and the tool
 * call proceeds, and the default window is shorter than a cold judge process needs.
 */
const HOOK_TIMEOUT = 60;
/** Lifecycle events routed through the same generated delegator, in generated-file order. */
const HOOK_EVENTS = ['PreToolUse', 'UserPromptSubmit', 'PostToolUse', 'SessionEnd'] as const;
type HookEvent = (typeof HOOK_EVENTS)[number];

/**
 * The generated hook. It carries no assembly at all, so upgrading the package upgrades the
 * judge without regenerating this file.
 */
const GENERATED_HOOK = `#!/usr/bin/env node
/**
 * Polydeukes PreToolUse covenant hook — generated by \`pdks-codex init\`.
 *
 * A delegator and nothing more: \`runHook\` builds the covenant input from this payload and
 * spawns \`pdks covenant check\`, so the judgment lives in the installed packages and this
 * file never needs regenerating.
 *
 * \`repoRoot\` comes from this file's own location, never from the working directory. A hook
 * is spawned with whatever directory the agent happened to hold, and what config discovery
 * and the package lookup need is the project that CONTAINS this hook — always \`../..\`
 * from here.
 *
 * fail-closed: \`runHook\` translates every failure it can reach into exit 2, with the row
 * written by the judge it spawns. This catch answers only for what it cannot reach — the
 * package failing to resolve or load at all (never installed, or installed without a
 * build) — where no telemetry writer exists yet. Recovery is installing the package again.
 *
 * Nothing is written to stdout here or by anything this file starts: the host parses a
 * hook's stdout as a decision document, and a field it does not accept marks the hook
 * failed and lets the tool call proceed.
 */

import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

try {
  const { runHook } = await import('${ADAPTER_SPECIFIER}');
  const { exitCode } = runHook({ repoRoot });
  // Assign and let the process end naturally instead of process.exit(): an explicit exit
  // can preempt a buffered stderr write on platforms with async pipes, dropping the break
  // reason the agent needs to read.
  process.exitCode = exitCode;
} catch (error) {
  console.error(\`covenant hook failed closed: \${error?.message ?? error}\`);
  process.exitCode = 2;
}
`;

type CommandHook = { type?: string; command?: string; timeout?: number };
type HookEntry = { matcher?: string; hooks?: CommandHook[] };

/** This installer's registration entry for one lifecycle event. */
function ownEntry(event: HookEvent): HookEntry {
  const hooks = [
    {
      type: 'command',
      command: HOOK_COMMAND,
      timeout: event === 'SessionEnd' ? 3 : HOOK_TIMEOUT,
    },
  ];
  return event === 'PreToolUse' || event === 'PostToolUse'
    ? { matcher: HOOK_MATCHER, hooks }
    : { hooks };
}

/** What one install left behind, per artifact. */
export type InitCodexReport = { created: string[]; skipped: string[] };

/** {@link initCodex} input — the target tree and its two seams. */
export type InitCodexSpec = {
  /** Project root to install into — every write below is relative to it. */
  projectRoot: string;
  /**
   * Preflight seam: the absolute path of the umbrella's `pdks` bin as reachable from the
   * given root, or a throw when the umbrella cannot be resolved there. ABSENT uses the real
   * resolution, anchored at that root and nowhere else — anchoring it at the installer's
   * own module would answer for the installer's install graph rather than the target
   * project's, which is precisely the case that must fail.
   */
  resolvePolydeukes?: (projectRoot: string) => string;
  /**
   * The `pdks init` spawn seam. ABSENT spawns node on the located bin with the child's
   * output inherited.
   */
  spawnScaffold?: (spec: { command: string; args: string[]; cwd: string }) => {
    status: number | null;
  };
};

/** The default preflight: where is `polydeukes` installed, as reachable from `projectRoot`? */
function resolveFromProjectRoot(projectRoot: string): string {
  const bin = findUmbrellaBin(projectRoot);
  if (bin === undefined) {
    throw new Error(`${UMBRELLA_PACKAGE} is not installed where this project can reach it`);
  }
  return bin;
}

/** Write one generated artifact unless it is already there, recording which happened. */
function writeIfAbsent(
  projectRoot: string,
  relative: string,
  contents: string,
  report: InitCodexReport,
): void {
  const path = join(projectRoot, relative);
  if (existsSync(path)) {
    report.skipped.push(relative);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, contents);
  report.created.push(relative);
}

/**
 * Add this installer's entry to the host's hook registration, keeping everything else.
 *
 * The file may already carry the user's own events, matchers, and keys, so it is merged
 * rather than written. Its own handler is found by the generated command, including on
 * matcherless events; sibling handlers in the same entry stay in place. A re-run produces
 * the same bytes, while an unreadable file throws rather than being overwritten or silently
 * skipped.
 */
function mergeRegistration(projectRoot: string, report: InitCodexReport): void {
  const path = join(projectRoot, JSON_RELATIVE);
  if (!existsSync(path)) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(
      path,
      `${JSON.stringify(
        { hooks: Object.fromEntries(HOOK_EVENTS.map((event) => [event, [ownEntry(event)]])) },
        null,
        2,
      )}\n`,
    );
    report.created.push(JSON_RELATIVE);
    return;
  }

  const existing: unknown = JSON.parse(readFileSync(path, 'utf-8'));
  if (!isPlainObject(existing)) {
    throw new Error(`${JSON_RELATIVE} is not a JSON object — repair it, then run this again`);
  }
  const hooks: Record<string, unknown> = isPlainObject(existing.hooks) ? existing.hooks : {};
  const mergedHooks: Record<string, unknown> = { ...hooks };

  for (const eventName of HOOK_EVENTS) {
    const entries = Array.isArray(hooks[eventName]) ? (hooks[eventName] as unknown[]) : [];
    const desired = ownEntry(eventName);
    let installed = false;
    const mergedEntries: unknown[] = [];

    for (const candidate of entries) {
      if (!isPlainObject(candidate) || !Array.isArray(candidate.hooks)) {
        mergedEntries.push(candidate);
        continue;
      }
      const handlers = candidate.hooks as unknown[];
      const ownsHandler = handlers.some(
        (handler) => isPlainObject(handler) && handler.command === HOOK_COMMAND,
      );
      if (!ownsHandler) {
        mergedEntries.push(candidate);
        continue;
      }

      const siblingHandlers = handlers.filter(
        (handler) => !(isPlainObject(handler) && handler.command === HOOK_COMMAND),
      );
      if (installed) {
        if (siblingHandlers.length > 0)
          mergedEntries.push({ ...candidate, hooks: siblingHandlers });
        continue;
      }

      if (siblingHandlers.length > 0 && candidate.matcher !== desired.matcher) {
        // A matcher belongs to the whole entry. Refreshing it in place would silently
        // widen or narrow the user's sibling handlers along with this generated command.
        mergedEntries.push({ ...candidate, hooks: siblingHandlers });
        mergedEntries.push(desired);
        installed = true;
        continue;
      }

      const updated: HookEntry = {
        ...candidate,
        hooks: [...(desired.hooks ?? []), ...siblingHandlers] as CommandHook[],
      };
      if (desired.matcher === undefined) delete updated.matcher;
      else updated.matcher = desired.matcher;
      mergedEntries.push(updated);
      installed = true;
    }

    if (!installed) mergedEntries.push(desired);
    mergedHooks[eventName] = mergedEntries;
  }

  const merged = {
    ...existing,
    hooks: mergedHooks,
  };
  // Written or not written, reported as such: a merge that appends this entry to a file the
  // user already had changes its trust hash, so calling it skipped would tell them nothing
  // needs approving while the hook sits unapproved and unjudging.
  const text = `${JSON.stringify(merged, null, 2)}\n`;
  if (text === readFileSync(path, 'utf-8')) {
    report.skipped.push(JSON_RELATIVE);
    return;
  }
  writeFileSync(path, text);
  report.created.push(JSON_RELATIVE);
}

/**
 * Install the Codex session surface into `spec.projectRoot`, skipping whatever is already
 * there and reporting both halves per artifact.
 *
 * Throws before any write when the umbrella cannot be resolved from that root or when the
 * scaffold refuses — both leave zero files. Translating a throw into exit 2 with the install
 * command is the bin's job.
 */
export function initCodex(spec: InitCodexSpec): InitCodexReport {
  const resolvePolydeukes = spec.resolvePolydeukes ?? resolveFromProjectRoot;
  let scaffoldBin: string;
  try {
    scaffoldBin = resolvePolydeukes(spec.projectRoot);
  } catch (error) {
    // The message names the package because the user's next action is installing it — the
    // seam's own message cannot be relied on to say so. The original is carried through
    // rather than discarded: an experimental resolver can fail for reasons that are
    // neither absence nor a stale version.
    throw new Error(
      `cannot use '${UMBRELLA_PACKAGE}' from ${spec.projectRoot} — install or update it there ` +
        `first (e.g. 'npm install --save-dev ${UMBRELLA_PACKAGE}'), then run this command ` +
        `again: ${error instanceof Error ? error.message : String(error)}`,
    );
  }

  const spawnScaffold =
    spec.spawnScaffold ??
    ((scaffold) =>
      spawnSync(scaffold.command, scaffold.args, { cwd: scaffold.cwd, stdio: 'inherit' }));
  const scaffold = spawnScaffold({
    command: process.execPath,
    args: [scaffoldBin, 'init'],
    cwd: spec.projectRoot,
  });
  if (scaffold.status !== 0) {
    // Any non-zero status is a scaffold that did not run: registering a delegator into a
    // tree with no config wires a judge whose every call fails closed.
    throw new Error(
      `'pdks init' failed in ${spec.projectRoot} (exit ${String(scaffold.status)}) — ` +
        'fix what it reported and re-run',
    );
  }

  const report: InitCodexReport = { created: [], skipped: [] };
  writeIfAbsent(spec.projectRoot, HOOK_RELATIVE, GENERATED_HOOK, report);
  mergeRegistration(spec.projectRoot, report);
  return report;
}
