/**
 * `scaffoldProject` — the project-side scaffold layer (DIST-02 §3-i).
 *
 * The half of an installation every distribution path shares: the data config the judges
 * read, and the telemetry ignore line. What differs between paths is REGISTRATION — how the
 * agent is told to spawn a judge at all — and that lives one layer up (`initClaudeCode` for
 * the `init` path, a manifest for the plugin one). The split is what lets a second path
 * reuse this function unchanged instead of scaffolding a config a second time, so nothing
 * that registers anything belongs here.
 *
 * Nothing existing is ever overwritten (§5-d invariant 1): an artifact that is already there
 * is reported and left alone. The config existence check reads all three discovery
 * candidates rather than the canonical name alone — writing `polydeukes.config.yaml` next to
 * a project's `.yml` makes {@link loadConfig} throw on ambiguity, and the fail-closed session
 * surface then blocks every call, so the installer itself would be what stopped the project.
 * Existence is FILE PRESENCE, never parse success: reading a broken config as "absent" would
 * destroy the very file the consumer was midway through fixing, and fixing it is their job.
 */

import { appendFileSync, existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { CONFIG_FILENAMES } from './load-config.js';

/** `.gitignore` name and the telemetry directory entry it must carry (§3-a). */
const GITIGNORE = '.gitignore';
const TELEMETRY_IGNORE_LINE = '.polydeukes/';
const GITIGNORE_ENTRY = `# Polydeukes telemetry — local observation data, never committed.\n${TELEMETRY_IGNORE_LINE}\n`;

/**
 * The generated config: the §3-d minimum protection set and the §3-e witness block, both
 * mandatory. Emitted as a literal template rather than serialized from an object because
 * the comments ARE the artifact — a consumer's first contact with the protection surface is
 * reading why each entry is on it.
 *
 * {@link schemaDirective} prepends the `yaml-language-server` line when the schema is where
 * that line would name it (DIST-05 §3-b).
 */
const GENERATED_CONFIG = `# Polydeukes protection policy — generated by \`pdks init claude-code\`.
#
# This file is data, never code. The judges read it, every verdict traces back to an entry
# below, and editing it is how you change what is judged.

# The language axis, the schema's one required block. \`init\` cannot know yours, so this is
# a placeholder: rename the key, point productionGlob at your own sources, and put your own
# verification command in testCmd (every literal {scope} is substituted at resolve time).
# No judgment path reads these values yet, so the placeholder cannot produce a wrong verdict
# while it waits to be edited.
languages:
  placeholder:
    productionGlob: 'src/**'
    testCmd: 'echo "set a verification command for {scope}"'

# The protection list. A tool call whose proven target is one of these paths is blocked, and
# so is a shell command that mentions one without a read-only head.
#
#   .claude/hooks, .claude/settings.json — the gate definitions themselves. Editing them
#     does not evade a judgment, it removes the judgment; the session surface is the only
#     layer that can watch it happen.
#
# A minimum. Add entries as you find you want them.
#
# This list is what blocks. Every \`disciplines:\` entry below lands at advise — a break is
# recorded and the call goes on — unless the entry itself says \`enforce: block\`.
protectedPaths:
  - '.claude/hooks'
  - '.claude/settings.json'

# The time-boxed witness — the human valve on a blocked verdict. A human types this token so
# it stands alone on a message's FIRST line, the window holds for ttlMinutes, then blocking
# resumes on its own. The valve is consulted only AFTER a verdict blocked, so an opened
# window is always recorded as \`witnessed\` and never silent, and no agent can open one for
# itself. The token is not a secret: the defence is provenance, not confidentiality.
#
# Keep this block. Without it no block can be opened by anyone, and .claude/hooks is on the
# list above — so the first block would freeze the project until a human edits these files
# from their own terminal.
witness:
  token: 'pdks witness'
  ttlMinutes: 10

# The disciplines you judge by, and the three rungs one climbs — shown as three entries so
# each rung is a line you can copy. Uncomment to start; ids must stay distinct.
#
# disciplines:
#   # A draft: prose only, no predicate. Registered and read, never judged.
#   - id: 'no-todo-in-shipped-code-draft'
#     why: 'a TODO nobody owns is a decision deferred out of sight'
#     draft: true
#
#   # Promoted to a judgment. Advise is the default — recorded as \`advised\`, never stops
#   # the call — so this line is optional; it is written here to show the rung.
#   - id: 'no-todo-in-shipped-code'
#     why: 'a TODO nobody owns is a decision deferred out of sight'
#     forbid: 'TODO'
#     enforce: advise
#
#   # The promotion — block is your choice, never the default.
#   - id: 'no-todo-in-shipped-code-blocking'
#     why: 'a TODO nobody owns is a decision deferred out of sight'
#     forbid: 'TODO'
#     enforce: block
`;

/**
 * Per-artifact outcome, as `projectRoot`-relative paths — the bin prints it (§3-a stdout
 * contract). `created` names what this run wrote, `skipped` what it found and left alone; a
 * silent skip would leave the user unable to tell an idempotent no-op from a failed run.
 */
export type ScaffoldReport = {
  created: string[];
  skipped: string[];
};

/**
 * Create the project-side artifacts of a Polydeukes installation in `projectRoot` (§3-i),
 * skipping whatever is already there.
 *
 * Throws when two or more config spellings coexist (§3-a third disposition) — that tree is
 * already stopped, since {@link loadConfig} refuses an ambiguous discovery, and adding
 * artifacts to it would wire a judge whose every call fails closed. The throw lands before
 * any write, so a human deleting one config is all it takes to reopen the path.
 */
/** The schema's path from a config sitting in `projectRoot`, as the directive spells it. */
const SCHEMA_REL = 'node_modules/polydeukes/dist/schema/polydeukes.schema.json';

/**
 * The `yaml-language-server` line for a config written into `projectRoot`, or nothing.
 *
 * An editor resolves a relative `$schema` against the config file's own directory, and this
 * command writes the config where it was invoked — so in a monorepo sub-package, whose install
 * hoisted to the workspace root, {@link SCHEMA_REL} names a path that is not there. The check
 * is one look at that exact path: present means the line an editor would follow leads to the
 * schema, absent means it leads nowhere, and a line leading nowhere is worse than none. An
 * unresolvable `$schema` produces no editor error and no validation, and a line the tool wrote
 * is not one its user thinks to audit.
 */
function schemaDirective(projectRoot: string): string {
  return existsSync(join(projectRoot, SCHEMA_REL))
    ? `# yaml-language-server: $schema=${SCHEMA_REL}\n`
    : '';
}

export function scaffoldProject(projectRoot: string): ScaffoldReport {
  const report: ScaffoldReport = { created: [], skipped: [] };

  const found = CONFIG_FILENAMES.filter((name) => existsSync(join(projectRoot, name)));
  if (found.length > 1) {
    throw new Error(
      `ambiguous Polydeukes config in ${projectRoot} — found ${found.join(' and ')}; ` +
        'keep exactly one and re-run',
    );
  }
  if (found.length === 1) {
    report.skipped.push(found[0]);
  } else {
    writeFileSync(
      join(projectRoot, CONFIG_FILENAMES[0]),
      schemaDirective(projectRoot) + GENERATED_CONFIG,
    );
    report.created.push(CONFIG_FILENAMES[0]);
  }

  // The entry is judged as a whole line. A substring test would treat a commented-out line
  // or a deeper path (`.polydeukes/roi.log`) as coverage and skip the append, leaving the
  // consumer committing their own telemetry — the failure that matters. Whole-line equality
  // errs the other way instead: a project already ignoring the directory under a different
  // spelling (`.polydeukes`, `/.polydeukes/`) gets a second, redundant entry. A duplicate
  // ignore rule costs a line; a missing one costs the consumer's telemetry. Appending is
  // also the only safe write — a `.gitignore` rewritten wholesale takes every entry the
  // consumer already relies on with it.
  const gitignorePath = join(projectRoot, GITIGNORE);
  const existing = existsSync(gitignorePath) ? readFileSync(gitignorePath, 'utf-8') : '';
  if (existing.split('\n').some((line) => line.trim() === TELEMETRY_IGNORE_LINE)) {
    report.skipped.push(GITIGNORE);
  } else {
    // A file that ends without a newline would otherwise absorb the entry into its last
    // line, breaking that entry while never forming ours.
    const separator = existing.length > 0 && !existing.endsWith('\n') ? '\n' : '';
    appendFileSync(gitignorePath, `${separator}${GITIGNORE_ENTRY}`);
    report.created.push(GITIGNORE);
  }

  return report;
}
