import { execSync, spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { afterEach, beforeAll, beforeEach, describe, expect, it } from 'vitest';

// `pdks init` on the built bin: the agent-neutral scaffold — the config file and the
// telemetry ignore line — in the directory the command was invoked from, and nothing else.
// The Claude Code registration is another package's installer, and the bin must refuse the
// old spelling rather than install something.

const repoRoot = resolve(import.meta.dirname, '../../..');
const BIN = resolve(import.meta.dirname, '../dist/bin.js');

const CONFIG_REL = 'polydeukes.config.yaml';
const GITIGNORE_REL = '.gitignore';
const GITIGNORE_LINE = '.polydeukes/';

let projectRoot: string;

beforeAll(() => {
  execSync('pnpm turbo run build', { cwd: repoRoot, stdio: 'pipe' });
}, 120_000);

beforeEach(() => {
  projectRoot = mkdtempSync(join(tmpdir(), 'pdks-init-scaffold-e2e-'));
});

afterEach(() => {
  rmSync(projectRoot, { recursive: true, force: true });
});

function pdks(...args: string[]) {
  return spawnSync(process.execPath, [BIN, ...args], { cwd: projectRoot, encoding: 'utf-8' });
}

describe('pdks init — the scaffold alone', () => {
  it('creates the config and the ignore line in the cwd, and prints both as created', () => {
    // The scaffold lands where the command ran. A config written anywhere else, or none,
    // leaves the project failing closed on its first judged call; a missing ignore line
    // commits the consumer's telemetry.
    const result = pdks('init');

    expect(result.status, result.stderr).toBe(0);
    expect(result.stdout).toContain(`created ${CONFIG_REL}`);
    expect(result.stdout).toContain(`created ${GITIGNORE_REL}`);
    expect(readdirSync(projectRoot).sort()).toEqual([GITIGNORE_REL, CONFIG_REL].sort());
    expect(readFileSync(join(projectRoot, GITIGNORE_REL), 'utf-8').split('\n')).toContain(
      GITIGNORE_LINE,
    );
  });

  it('writes a config header that names `pdks init` and not the removed spelling', () => {
    // The header is the consumer's first contact with the tool; naming a command the bin
    // now refuses sends them to a usage error.
    pdks('init');

    const config = readFileSync(join(projectRoot, CONFIG_REL), 'utf-8');
    expect(config).toContain('generated by `pdks init`');
    expect(config).not.toContain('init claude-code');
  });

  it('reports both artifacts as skipped on a re-run and leaves them byte-identical', () => {
    // An ignore line appended unconditionally grows .gitignore by one line per run; a
    // config rewritten resets the consumer's edits. The stdout report is how the user
    // tells a no-op from a failed run.
    pdks('init');
    const config = readFileSync(join(projectRoot, CONFIG_REL), 'utf-8');
    const gitignore = readFileSync(join(projectRoot, GITIGNORE_REL), 'utf-8');

    const second = pdks('init');

    expect(second.status).toBe(0);
    expect(second.stdout).toContain(`skipped ${CONFIG_REL} (already present)`);
    expect(second.stdout).toContain(`skipped ${GITIGNORE_REL} (already present)`);
    expect(second.stdout).not.toMatch(/^created /m);
    expect(readFileSync(join(projectRoot, CONFIG_REL), 'utf-8')).toBe(config);
    expect(readFileSync(join(projectRoot, GITIGNORE_REL), 'utf-8')).toBe(gitignore);
  });

  it('refuses `init claude-code` with usage on stderr, exit 2, and no files', () => {
    // The old spelling must not fall through to the bare scaffold: a consumer following a
    // stale instruction would get a config and believe the session surface was registered.
    const result = pdks('init', 'claude-code');

    expect(result.status).toBe(2);
    expect(result.stderr).toMatch(/usage/i);
    expect(existsSync(join(projectRoot, CONFIG_REL))).toBe(false);
    expect(readdirSync(projectRoot)).toEqual([]);
  });
});
